[app]
base_resolution = [1280, 720]
rng_seed = 1000

[game]
selected_texture_pack = "default"
friction = 100.0

[game.texture_packs.default]
root = "sprites"

[[game.texture_packs.default.texture_map.AllPlayers.Choose]]
path = "player_skin_tone_a.png"
grid_dimensions = [4, 1]
cell_resolution = [128, 128]

[[game.texture_packs.default.texture_map.AllPlayers.Choose]]
path = "player_skin_tone_b.png"
grid_dimensions = [4, 1]
cell_resolution = [128, 128]

[[game.texture_packs.default.texture_map.AllPlayers.Choose]]
path = "player_skin_tone_c.png"
grid_dimensions = [4, 1]
cell_resolution = [128, 128]

[[game.texture_packs.default.texture_map.AllPlayers.Choose]]
path = "player_skin_tone_d.png"
grid_dimensions = [4, 1]
cell_resolution = [128, 128]

[[game.texture_packs.default.texture_map.Supervisor.Choose]]
path = "supervisor_skin_tone_a.png"
grid_dimensions = [2, 1]
cell_resolution = [128, 128]

[[game.texture_packs.default.texture_map.Supervisor.Choose]]
path = "supervisor_skin_tone_b.png"
grid_dimensions = [2, 1]
cell_resolution = [128, 128]

[[game.texture_packs.default.texture_map.Supervisor.Choose]]
path = "supervisor_skin_tone_c.png"
grid_dimensions = [2, 1]
cell_resolution = [128, 128]

[[game.texture_packs.default.texture_map.Supervisor.Choose]]
path = "supervisor_skin_tone_d.png"
grid_dimensions = [2, 1]
cell_resolution = [128, 128]

[game.texture_packs.default.texture_map.Package.Only]
path = "box.png"

[game.texture_packs.default.texture_map.Conveyor.Only]
path = "conveyor.png"
grid_dimensions = [5, 1]
cell_resolution = [128, 128]

[game.texture_packs.default.texture_map.Background.Only]
path = "background.png"

[game.texture_packs.default.texture_map.SupervisorOffice.Only]
path = "supervisor_office.png"

[game.texture_packs.default.texture_map.ScoreDisplay.Only]
path = "display.png"

[game.team_colour.RgbaLinear]
red = 0.6000000238418579
green = 0.10000000149011612
blue = 0.6000000238418579
alpha = 1.0

[game.player_config]
size = 30.0
move_speed = 150.0
sprint_move_modifier = 2.0
throw_power = 15.0

[game.player_config.per_player.Player1.colour.RgbaLinear]
red = 1.0
green = 0.30000001192092896
blue = 0.30000001192092896
alpha = 1.0

[game.player_config.per_player.Player1.sprite_override.Only]
path = "sprites/custom_player.png"
grid_dimensions = [4, 1]
cell_resolution = [128, 128]

[game.player_config.per_player.Player1.key_map.MoveUp.priamry]
Key = "KeyW"

[game.player_config.per_player.Player1.key_map.MoveUp.secondary]
ControllerAxis = ["LeftStickY", "Positive"]

[game.player_config.per_player.Player1.key_map.MoveDown.priamry]
Key = "KeyS"

[game.player_config.per_player.Player1.key_map.MoveDown.secondary]
ControllerAxis = ["LeftStickY", "Negative"]

[game.player_config.per_player.Player1.key_map.MoveLeft.priamry]
Key = "KeyA"

[game.player_config.per_player.Player1.key_map.MoveLeft.secondary]
ControllerAxis = ["LeftStickX", "Negative"]

[game.player_config.per_player.Player1.key_map.MoveRight.priamry]
Key = "KeyD"

[game.player_config.per_player.Player1.key_map.MoveRight.secondary]
ControllerAxis = ["LeftStickX", "Positive"]

[game.player_config.per_player.Player1.key_map.Sprint.priamry]
Key = "ShiftLeft"

[game.player_config.per_player.Player1.key_map.Sprint.secondary]
ControllerAxis = ["LeftZ", "Positive"]

[game.player_config.per_player.Player1.key_map.PickupOrThrow.priamry]
Key = "Space"

[game.player_config.per_player.Player1.key_map.PickupOrThrow.secondary]
ControllerAxis = ["RightZ", "Positive"]

[game.player_config.per_player.Player2.colour.RgbaLinear]
red = 0.30000001192092896
green = 0.30000001192092896
blue = 1.600000023841858
alpha = 1.0

[game.player_config.per_player.Player2.key_map.MoveUp.priamry]
Key = "ArrowUp"

[game.player_config.per_player.Player2.key_map.MoveUp.secondary]
ControllerAxis = ["LeftStickY", "Positive"]

[game.player_config.per_player.Player2.key_map.MoveDown.priamry]
Key = "ArrowDown"

[game.player_config.per_player.Player2.key_map.MoveDown.secondary]
ControllerAxis = ["LeftStickY", "Negative"]

[game.player_config.per_player.Player2.key_map.MoveLeft.priamry]
Key = "ArrowLeft"

[game.player_config.per_player.Player2.key_map.MoveLeft.secondary]
ControllerAxis = ["LeftStickX", "Negative"]

[game.player_config.per_player.Player2.key_map.MoveRight.priamry]
Key = "ArrowRight"

[game.player_config.per_player.Player2.key_map.MoveRight.secondary]
ControllerAxis = ["LeftStickX", "Positive"]

[game.player_config.per_player.Player2.key_map.Sprint.priamry]
Key = "ShiftRight"

[game.player_config.per_player.Player2.key_map.Sprint.secondary]
ControllerAxis = ["LeftZ", "Positive"]

[game.player_config.per_player.Player2.key_map.PickupOrThrow.priamry]
Key = "ControlRight"

[game.player_config.per_player.Player2.key_map.PickupOrThrow.secondary]
ControllerAxis = ["RightZ", "Positive"]

[game.supervisor_config]
size = 30.0
monitoring_y_pos = 285.0
office_sprite_size = [400, 150]

[game.conveyor_config]
size = [128.0, 500.0]
speed = 100.0
border_size = 14.0
blinker_size = 20.0
blink_duration_seconds = 0.10000000149011612

[game.package_config]
size = 30.0
base_score_value = 5.0

[game.score_config]
multiplier_increase_per_package = 0.10000000149011612
multiplier_decrease_per_second = 0.10000000149011612
